### ISSUE TITLE
Search Engine Optimization

### ISSUE THREAD

**Issue by MaxHillebrand** [zkSNACKs/WasabiDoc#40]
As suggested in the [VuePress documentation](https://vuepress.vuejs.org/guide/markdown.html#front-matter), each markdown file can have some meta data in yaml format at the top of the file. This can include upon others a description and keywords. I'm not entirely sure how this will affect SEO only for the internal search box, or also for duck duck go searches.

As example the `/FAQ-UseWasabi.md`:

```
---
meta:
  - name: description
    content: Frequently Asked Questions how to use Wasabi Wallet.
  - name: keywords
    content: faq how-to use wasabi bitcoin wallet generate load receive send history coinjoin hardware settings coin-control 
---
```
