### ISSUE TITLE
Add logo in navbar and favicon

### ISSUE THREAD

**Issue by MaxHillebrand** [zkSNACKs/WasabiDoc#42]
As described in the [VuePress documentation](https://vuepress.vuejs.org/default-theme-config/#navbar-logo), we can add the wasabi logo in the navbar like this:

```
// .vuepress/config.js
module.exports = {
  themeConfig: {
    logo: '/assets/img/logo.png',
  }
}
```

### ToDo
- [x] navbar logo
- [x] favicon

**Comment by thunderBiscuit** [comment]
@MaxHillebrand I was going to open a pull request for this but I realize it's only one line in the config file. Do you wish to integrate it yourself without a full PR for it? I think the default size for the logo is pretty good; let me know what you think. If we wish to change it it's a bit more work because we have to go and play with the css so I'll open a full PR for that (if needed).

Right under `[themeConfig]` you include the line `logo = '/Logo_without_text.png'`. It would look something like this:

```toml
title = "Wasabi Documentation"
description = "Wasabi is an open-source... "

[themeConfig]
logo = '/Logo_without_text.png'
displayAllHeaders = false
sidebarDepth = 0
repo = "zkSNACKs/WasabiDoc"
editLinks = true

    # why Wasabi sidebar
    # ----------------------------------------
    [[themeConfig.sidebar."/why-wasabi/"]]

    # ...
    # rest of the config file
```
